### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Alejandro-Trave-formulario-HTML5#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen proyecto @Atravep   ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- El atributo `type` en los elementos `<input>` define el tipo de control de entrada que se mostrará al usuario (pueden ser `text`, `number`, `password`, `email`), ... Revísalos porque en el "CVC" sólo nos tendría que dejar introducir números, en el "First name" y "Last name" sólo nos tendría que dejar introducir texto, etc

![Captura de pantalla de 2024-03-14 16-52-37](https://github.com/4GeeksAcademy/Alejandro-Trave-formulario-HTML5/assets/139759297/d8dd3838-cd4f-4cca-adc7-9a9d0c38ae6c)

**Comment by Atravep** [comment]
# Respuesta con estilo

**OMG**
Olvidé totalmente especificar los type en los input!!🤦‍♂️ Tomo nota! 

```php{
while (true) {
Shame on me!
}
```

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo
